# Generated by Django 4.2 on 2024-10-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digimon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
